apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-jonathan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-jonathan
      version: v1
  template:
    metadata:
      labels:
        app: portfolio-jonathan
        version: v1
    spec:
      containers:
        - image: lhr.ocir.io/lrwuubtwxjma/constellation-images/jonno-personal-frontend:latest
          imagePullPolicy: Always
          name: portfolio-jonathan
          resources:
            requests:
              memory: "128Mi"
              cpu: 0.1
            limits:
              memory: "256Mi"
              cpu: 0.2
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      imagePullSecrets:
        - name: ocirsecret
