apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: portfolio-jonathan
spec:
  parentRefs:
    - name: constellation-gateway
      sectionName: https-jonnowang
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: portfolio-jonathan
          port: 4321
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
