apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: personal-codeserver
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/apps/codeserver
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
