apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: personal-codeserver
  namespace: default
spec:
  parentRefs:
    - name: constellation-gateway
      sectionName: https-jonnowang-code
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: personal-codeserver
          port: 8443
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
