apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: codeserver-password
  namespace: default
spec:
  encryptedData:
    foo: AgB5Ta2y9d0cv7KpwbflN6k6XCOtH1TADqxY8isjeRh8AL/fnqyM/CbnAQrAKER6v5KpMM6jPWK2dB8pVWYTX5DxGmlYRJoiRcVMY+pxrXokuJTptZpPByFCi/GkUVDALi/H1V6HHy/yApzETO/CCZiCI2k38Dtc2U1dm8THbRnr2gZw+Vg55WHtTo7nS+qYoG4r4A+w3+/hK4lrslYJ3Nzi5z3w1YVSvl6HpUDhnusstCgIQNeCcXhBu6g3c8Hik6pRqB7Iy5OjvjnWaFcgDm0rLqELTOX7+HPI40sqdiEDMN6WXeUWxho11vbMEainYamH/xmlakjPZKi35wX/S2aavfcJ5LlWiSpnztiHzzo8g9827bcjdXUscyTawzfw5Z7mTLqfHl6gfHN79hhRN5os13fj9eT+xgXrIIor+J+CyRmPKBP6oqEkNr/6xYHOfMN/dR+VBMxix65Qkco9OrMEbfsPX0EuKCtWwCcZm7RKRAhuBRci2q1VSLrlQn/ls06qmUtQVILZWoXmvld+rlSmrQ1PoMTWE+fufaEFQWfbBJHccMUlX3AZs4w9spYiprrPtnihytkt1s8RKXp6w3Q7JaIDKEpomjCm5ePCqDtzR5Gb+nh4MDWot/4okudGV4nQKMKRiyi174atSFBu1eXUkI2N3+yAYVGtjvkbC5Y1C9PNB3txjAafQErkasV2takZDal6z5tQYlARJWM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: codeserver-password
      namespace: default
