apiVersion: v1
kind: Service
metadata:
  name: personal-codeserver
  namespace: default
  labels:
    app: personal-codeserver
    service: personal-codeserver
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8443
      targetPort: 8443
  selector:
    app: personal-codeserver
