apiVersion: v1
kind: Service
metadata:
  name: chronoseal
  namespace: default
  labels:
    app: chronoseal
    service: chronoseal
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: chronoseal
