apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    service: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 80
  selector:
    app: backend
